"""Initial schema

Revision ID: 001
Revises:
Create Date: 2026-03-21 12:30:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attestation_type', sa.String(length=50), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=False),
    sa.Column('operator_ip', postgresql.INET(), nullable=False),
    sa.Column('consent_text_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consent_record_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_name_hash', sa.String(length=64), nullable=True),
    sa.Column('input_email_hash', sa.String(length=64), nullable=True),
    sa.Column('input_username', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('modules_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operator_ip', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight_applied', sa.Float(), nullable=False),
    sa.Column('remediation_action', sa.Text(), nullable=False),
    sa.Column('remediation_effort', sa.String(length=20), nullable=False),
    sa.Column('remediation_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_nodes',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=500), nullable=False),
    sa.Column('profile_url', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_node_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_node_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_edges')
    op.drop_table('graph_nodes')
    op.drop_table('findings')
    op.drop_table('audit_logs')
    op.drop_table('scans')
    op.drop_table('consent_records')
    # ### end Alembic commands ###